# name: "AccuKnox Container Scanner"
# description: "Run AccuKnox Container Security scan on a container image"

# inputs:
#   token:
#     description: "The token for authenticating with the CSPM panel."
#     required: true
#   label:
#     description: "The label created in AccuKnox SaaS for associating scan results."
#     required: true
#   endpoint:
#     description: "The URL of the CSPM panel to push the scan results to."
#     required: true
#   image_name:
#     description: "Docker image name to scan"
#     required: true
#   tag:
#     description: "Docker image tag (optional)"
#     required: false
#     default: ""
#   severity:
#     description: "Comma-separated severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
#     required: false
#     default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
#   soft_fail:
#     description: "Do not return an error code if there are failed checks"
#     required: false
#     default: false

# runs:
#   using: "composite"
#   steps:
#     - name: Run AccuKnox Container Scan
#       shell: bash
#       env:
#         ACCUKNOX_TOKEN: ${{ inputs.token }}
#         ACCUKNOX_LABEL: ${{ inputs.label }}
#         ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
#         IMAGE_NAME: ${{ inputs.image_name }}
#         TAG: ${{ inputs.tag }}
#         SEVERITY: ${{ inputs.severity }}
#         SOFT_FAIL: ${{ inputs.soft_fail }}
#       run: |
#         set -e

#         if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
#           echo "ERROR: token, label, endpoint, and image_name must be provided!"
#           exit 1
#         fi

#         echo "Downloading AccuKnox ASPM Scanner..."
#         curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
#         chmod +x accuknox-aspm-scanner

#         echo "Installing container scan tool..."
#         ./accuknox-aspm-scanner tool install --type container

#         if [ "$SOFT_FAIL" = "true" ]; then
#           SOFT_FAIL_ARG="--softfail"
#         fi

#         # Build scan command dynamically
#         CMD="image $IMAGE_NAME"
#         [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
#         [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"

#         echo "Running AccuKnox container scan:"
#         echo "./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command \"$CMD\" --container-mode"
#         ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command "$CMD" --container-mode


name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container Security scan on a container image"

inputs:
  token:
    description: "The token for authenticating with the CSPM panel."
    required: true
  label:
    description: "The label created in AccuKnox SaaS for associating scan results."
    required: true
  endpoint:
    description: "The URL of the CSPM panel to push the scan results to."
    required: true
  image_name:
    description: "Docker image name to scan"
    required: true
  tag:
    description: "Docker image tag (optional)"
    required: false
    default: ""
  severity:
    description: "Comma-separated severities: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  soft_fail:
    description: "Do not return an error code if there are failed checks"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scan
      shell: bash
      env:
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        IMAGE_NAME: ${{ inputs.image_name }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
      run: |
        set -e

        if [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$IMAGE_NAME" ]; then
          echo "ERROR: token, label, endpoint, and image_name must be provided!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Installing container scan tool..."
        ./accuknox-aspm-scanner tool install --type container

        # Clean up SOFT_FAIL and normalize to lowercase
        SOFT_FAIL="${SOFT_FAIL,,}"
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"
        SOFT_FAIL_ARG=""
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Build scan command dynamically
        CMD="image $IMAGE_NAME"
        [ -n "$TAG" ] && CMD="image $IMAGE_NAME:$TAG"
        [ -n "$SEVERITY" ] && CMD="$CMD --severity $SEVERITY"

        echo "Running AccuKnox container scan:"
        echo "./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command \"$CMD\" --container-mode"
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG container --command "$CMD" --container-mode
